-- Jadara Consulting Platform — Phase 5: AI insights.
-- Run in the Supabase SQL editor for project gjuzaafqfsvmxhumpokp, after 006_consulting_studio.sql.
-- Safe to re-run. Additive only.

-- ============================================================
-- consulting_insights — a history row per AI generation call, kept
-- separate from consulting_sections.config (which stays the live/current
-- editable content, same as it was pre-Phase-5). This is what lets us show
-- "generated by AI, from this exact set of computed facts" as a durable
-- record even after an editor later rewrites the section by hand — the
-- current text lives in consulting_sections.config.body as before.
-- ============================================================
create table if not exists consulting_insights (
  id bigserial primary key,
  deliverable_id bigint not null references consulting_deliverables(id) on delete cascade,
  section_id bigint not null references consulting_sections(id) on delete cascade,
  content text not null,
  status text not null default 'ai_generated' check (status in ('ai_generated', 'edited')),
  generated_by_model text,
  source_summary jsonb,
  created_by uuid references profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_consulting_insights_section on consulting_insights (section_id, created_at desc);
create index if not exists idx_consulting_insights_deliverable on consulting_insights (deliverable_id);

alter table consulting_insights enable row level security;

drop policy if exists "consulting_insights_staff_all" on consulting_insights;
create policy "consulting_insights_staff_all" on consulting_insights
  for all to authenticated using (true) with check (true);

-- Note: consulting_sections.config already stores per-section state as
-- jsonb, so the "AI-generated vs. manually edited" status badge doesn't
-- need a new column — the frontend reads/writes config.ai_status directly
-- (see admin/js/modules/studio/ai-insights.js and studio-editor.js).
